name: check PR Links

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Check links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          # Remap live URLs to build directory because the links are potentially not live (not yet on master)
          args: |
            --verbose 
            --no-progress
            --exclude-all-private
            --exclude-path '(^|/)docs/'
            --retry-wait-time 5
            ./
          fail: true

      - name: Suggestions
        if: failure()
        run: |
          echo -e "\nPlease review the links reported in the 'Check links' step above."
          echo -e "If a link is valid but fails due to a CAPTCHA challenge, IP blocking, login requirements, etc.,"
          echo -e "consider adding such links to .lycheeignore file to bypass future checks.\n"
          exit 1
