name: Tests matrix

permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.26"
          - "1.25"
        clickhouse: # https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions
          - "26.7"
          - "26.6"
          - "26.5"
          - "26.3"
          - "25.8" # LTS
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go }}

      - name: Tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
          GOTOOLCHAIN: "local"
        run: |
          CLICKHOUSE_VERSION=${{ matrix.clickhouse }} make test
